# Generated by Django 3.0.8 on 2020-09-20 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('browser', models.CharField(max_length=255, verbose_name='Браузер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История входа в систему',
                'verbose_name_plural': 'Истории входа в систему',
            },
        ),
    ]
