# Generated by Django 3.0.8 on 2020-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200921_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='ip',
            field=models.CharField(default=1, max_length=255, verbose_name='IP адрес'),
            preserve_default=False,
        ),
    ]
