# Generated by Django 3.0.8 on 2020-09-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loginhistory_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
    ]
