# Generated by Django 3.0.8 on 2020-09-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200922_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_completed',
            field=models.BooleanField(default=False, verbose_name='Обучение завершено'),
        ),
    ]
