# Generated by Django 3.0.8 on 2020-09-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_training_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenConfirmEmail',
        ),
    ]
