# Generated by Django 3.0.8 on 2020-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('user', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['-id', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MasterPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Мастер пароль',
                'verbose_name_plural': 'Мастер пароли',
            },
        ),
    ]
